### ISSUE TITLE
Extraneous prefixes emitted with no (obvious) way to remove them

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/dclib#42]
Taking a minimal template:

```yaml
name: prefixes-test
type: Composite
```

and minimal source data:

```csv
t1,t2
1,2
```

The output from `dclib prefixes-test.yaml source.csv` is:

```turtle
@prefix void:  <http://rdfs.org/ns/void#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix org:   <http://www.w3.org/ns/org#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix version: <http://purl.org/linked-data/version#> .
@prefix qb:    <http://purl.org/linked-data/cube#> .
@prefix at:    <http://environment.data.gov.uk/public-register/def/applicant-type/> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix reg:   <http://purl.org/linked-data/registry#> .
@prefix time:  <http://www.w3.org/2006/time#> .
@prefix api:   <http://purl.org/linked-data/api/vocab#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .
```

Some of these are fine in general use, but some are less commonly needed  (e.g. `reg`, `qb`) and some are not really needed at all except in very specific circumstances (e.g. `at`).

As far as I can tell, setting the `prefixes` option in the template file adds to the set of known prefixes, but does not remove any of the default set.

It would be nice if there was a mechanism (e.g. by command line option or a config setting) to suppress the built-in default prefixes, and only use those specified in the template 

I'm currently using DCLIb `2.1.2-SNAPSHOT`

**Comment by der** [comment]
It looks for a file `defaultPrefixes.ttl` in the current directory which, if I recall correctly, replaces the built-in fall back defaults. Then the template ones are additive.

**Comment by der** [comment]
Would agree that the documentation of that seems rather lacking :)

**Comment by ijdickinson** [comment]
Great, thanks @der
