### ISSUE TITLE
toCleanSegement() and full-stops

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/dclib#47]
I have some source values like `"v.high"` and `"v.low"`. If I call `toCleanSegment()` on those, the full-stop character is not converted. I'm not sure if that's by-design or accidental, but it would be nice if there was at least an option to generate `"v-high"` as a segment value.

**Comment by der** [comment]
That's because `.` are legal URIs (I think). Can always regex it away.

**Comment by ijdickinson** [comment]
Ah, good point about using regex. I should have thought of that!
